#!/bin/sh
# формат вызова listdbdump -ip <IP_адрес_сервера> --p <порт1 порт2 ... портN>
while [ -n "$1" ]
do
case "$1" in
-ip) export Host="$2"
shift ;;
--p) shift
break ;;
*) echo "$1 is not an option";;
esac
shift
done
DUMPDIR=/var/lib/pgsql/data
for Port in "$@"
do
  for dbname in `psql -d template1 -q -U postgres -h $Host -p $Port -t  <<EOF
    select datname from pg_database where not datname in ('bacula','template0') order by datname;
EOF
`
  do
    if [[ $Port == 5432 ]]
    then
      echo "$DUMPDIR/main/dump/$dbname.sql"
    elif [[ $Port == 5433 ]]
    then
      echo "$DUMPDIR/zud/dump/$dbname.sql"
    else
    echo "Порт $Port не поддерживает соединения с БД"
    exit 1
    fi
  done
done
