#!/bin/sh
DUMPDIR=/var/lib/pgsql/data
for Port in {$2,$3}
do
  for dbname in `psql -d template1 -q -U postgres -h $1 -p $Port -t  <<EOF
    select datname from pg_database where not datname in ('bacula','template0') order by datname;
EOF
`
  do
    if [[ $Port == 5432 ]]
    then
      echo "$DUMPDIR/main/dump/$dbname.sql"
    elif [[ $Port == 5433 ]]
    then
      echo "$DUMPDIR/zud/dump/$dbname.sql"
    else
      echo "Порт $Port не поддерживает соединения с БД"
      exit 1
    fi
  done
done
