#!/bin/sh
exec &> /dev/null
PGUSER=postgres
PGPWD=11111111
DIR=/var/lib/pgsql/data/main/dump
rm -f $DIR/*.*
for dbname in "$@"
do
/usr/bin/pg_dump -p 5432 -U $PGUSER --disable-macs -d $dbname --file=$DIR/$dbname.sql 2>&1 < /dev/null &
wait
done
exit=0
