#!/bin/sh
exec &> /dev/null
DIR=/var/lib/pgsql/data/
export PGUSER=postgres
export PGPWD=11111111
export dbname=$1
FIFODIR=$DIR/main/dump
rm -f $FIFODIR/$dbname.sql
/usr/bin/pg_dump -U $PGUSER -c -C -d $dbname --file=$FIFODIR/$dbname.sql # 2>&1 < /dev/null &
wait
exit=0
